server:
  port: 2345
  context-path:
spring:
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb
appInfo:
  filePath: E:/upload/voice/
  webPath:
baidu:
  appId: 
  apiKey:
  secretKey: