server:
  port: 2345
  context-path:
spring:
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb
appInfo:
  filePath: E:/upload/voice/
  webPath:
baidu:
  appId: 11248105
  apiKey: D3c4wwLMXRghmC9Pbo1vZd7Y
  secretKey: ZboY00wCjBNPHaDsl2fWkhBU2IDhf89H